name:                task
version:             0.1.0.0
license:             Unlicense

dependencies:
  - base

default-extensions:
  - EmptyDataDeriving
  - DerivingStrategies

library:
  source-dirs:      src

tests:
  task-tests:
    source-dirs:      test
    main: Main.hs
    dependencies:
    - tasty
    - tasty-hspec
    - hspec
    - task
